### ISSUE TITLE
General Wiki Information.

### ISSUE THREAD

**Issue by ankitvad** [the-xkcd-community/the-red-spider-project#81]
Could someone list out exactly how many Ideas in the Wiki are still open to do/implement ? Uassigned/Not-Implemented or otherwise ?

**Comment by jgonggrijp** [comment]
Hello @ankitvad , thank you for your interest!

The list of free ideas is completely up-to-date, actually. All ideas listed are available for you to execute (neither assigned nor implemented) and similar efforts are mentioned where applicable. Ongoing efforts tend to be mentioned in the issue tracker.
